### ISSUE TITLE
add reposync/createrepo for yum

### ISSUE THREAD

**Issue by zhsj** [ustclug/ustcmirror-images#10]
https://github.com/rpm-software-management/yum
https://github.com/rpm-software-management/yum-utils
https://github.com/rpm-software-management/createrepo
https://github.com/rpm-software-management/createrepo_c

**Comment by taoky** [comment]
我正在尝试把 TUNA 的 https://github.com/tuna/tunasync-scripts/blob/master/yum-sync.py 移植过来。在搜索资料的时候发现，`reposync` 似乎本身有下载 metadata 的功能，不需要 `createrepo` 来创建，不太确定具体同步的时候应该怎么配置。
