### ISSUE TITLE
add jigdo mirror

### ISSUE THREAD

**Issue by zhsj** [ustclug/ustcmirror-images#16]
mirrors 上用的 cd-mirror 脚本应该来自 http://www.acc.umu.se/~maswan/debian-push/cdimage/
依赖 jigdo

**Comment by gaoyifan** [comment]
acc上的脚本已经非常老了。最新版在这里：http://ftp.mgts.by/debian-mirror/cdimage/

**Comment by zhsj** [comment]
acc 上有个目录叫 new。。
http://www.acc.umu.se/~maswan/debian-push/cdimage/new/
