### ISSUE TITLE
Logo design contribution

### ISSUE THREAD

**Issue by reallinfo** [ustclug/ustcmirror-images#48]
Hello,

I am a graphic designer. I contribute to open source software by designing a logo. I can design logo for this repo. What do you think? 

you can see many logo design examples on my github profile.

https://github.com/reallinfo

**Comment by knight42** [comment]
Hi @reallinfo, sorry for the delay.

It's fantastic that you would like to design a logo for us. Since I have no idea what the logo should look like now, please let me know if you need any help.

Your work would be greatly appreciated. Thank you!

**Comment by reallinfo** [comment]
![ustc](https://user-images.githubusercontent.com/36298335/41049985-d17a1a4a-69ba-11e8-8651-466ab91aa968.jpg)

I designed a few logo. how do these look?

**Comment by knight42** [comment]
well... it looks fine, but I think it could be more expressive. 

The images we created in this repo could "sync" files and directories from the upstream in various ways, and IMO "syncing" is a key point here. I hope it could be reflected in the logo. In addition, the logo of our organization is not mandatory, just free your mind.
