### ISSUE TITLE
把默认的 base alpine 镜像升级到 3.11

### ISSUE THREAD

**Issue by knight42** [ustclug/ustcmirror-images#61]
目前有的同步方式依赖 alpine 3.11 https://github.com/ustclug/ustcmirror-images/blob/9b24016a60b990512c0896a1aed3df8b7818337f/base/Dockerfile.alpine-3.11#L1-L2 ，而现在默认的 base alpine 镜像用的是 3.7。可以考虑统一升级到 3.11 避免维护多个版本。

**Comment by taoky** [comment]
在半个多月前的 10e7844690c8b7fd49c3384365aff9873137fb2c 中完成了升级，目前看起来同步没有问题。

**Comment by knight42** [comment]
@taoky 唔 https://github.com/ustclug/ustcmirror-images/commit/10e7844690c8b7fd49c3384365aff9873137fb2c 这个 commit 里把 `base/Dockerfile.alpine-3.6` 这个 Dockerfile 删掉了，但我们 ustc 镜像站上用的应该还是 lftpsync-alpine-3.6，它的 Dockerfile 依赖 base:alpine-3.6 https://github.com/ustclug/ustcmirror-images/blob/master/lftpsync/Dockerfile.alpine-3.6 。感觉是不是应该删掉 `base/Dockerfile.alpine-3.11` ？

至于为什么镜像站上用的还是 lftpsync-alpine-3.6，确切的原因我不太记得了，只隐约记得是 lftp 的行为发生了改变，你们有空的话可以验证一下。

**Comment by taoky** [comment]
留着 `base/Dockerfile.alpine-3.11` 的原因是目前 Homebrew 依赖 Ruby 2.6，更新/更老的 Alpine 中的 Ruby 不是这个版本，会让 homebrew 自己下载 ruby，然后之前测试的结果是安装会失败，所以这个文件就留着了。

lftp 的问题我有空看一下。

**Comment by taoky** [comment]
现在的情况是，同步:

- node
- nginx
- mysql-repo
- centos-cloud
- openresty
- steamos
- influxdata
- msys2
- wine

用的是 `lftpsync:latest`，只有 docker-ce 的同步还是使用 `lftpsync:alpine-3.6`。

**Comment by taoky** [comment]
> 现在的情况是，同步:
> 
> * node
> * nginx
> * mysql-repo
> * centos-cloud
> * openresty
> * steamos
> * influxdata
> * msys2
> * wine
> 
> 用的是 `lftpsync:latest`，只有 docker-ce 的同步还是使用 `lftpsync:alpine-3.6`。

我刚刚试了一下，终于知道为什么要用 `lftpsync:alpine-3.6` 了：download.docker.com 的文件列表和其他站点都不太一样：

- 首页的 `linux` 和 `mac` 结尾没有 slash：导致默认参数下 rclone 只会同步两个叫 `linux` 和 `mac` 的文件。
- 不会把 URL 中 `//` 解析为 `/`，例如 <https://download.docker.com/linux> 是正常的，但是 <https://download.docker.com//linux> 会挂掉：这导致了新版本的 lftp 的 mirror 会直接挂掉。
- 有一些「文件夹」会 301 到其他目录：rclone 无法处理这种情况（最新的 1.53.3 也是这样）

测试的结果是现在 docker-ce/ 目录所有文件都被新版 lftp 删掉了，现在正在恢复中……
