### ISSUE TITLE
Question. Should aptsync run on RHEL with podman? [SOLVED]

### ISSUE THREAD

**Issue by RudiOnTheAir** [ustclug/ustcmirror-images#78]
Tried to get Debian Repos (Bullseye) and write to local /var/www/html/debian. But get "Error: statfs /var/spool/apt-mirror: no such file or directory"

The /var/spool path is inside the container??

docker run --rm \
    -e LOG_ROTATE_CYCLE='5' \
    -e APTSYNC_URL='ftp.de.debian.org/debian' \
    -e APTSYNC_DISTS='bullseye|main contrib|amd64' \
    -v /var/spool/apt-mirror:/var/www/html/debian \
    docker.io/ustcmirror/aptsync:latest

Thanks in advance

**Comment by zhsj** [comment]
I think it should be `-v /var/www/html/debian:/data`

**Comment by knight42** [comment]
@RudiOnTheAir Hi! `aptsync` should be able to run inside the container regardless of the distribution of the host environment.

As a complement to what @zhsj suggests, you could try the following command:
```
docker run --rm \
-e LOG_ROTATE_CYCLE='5' \
-e APTSYNC_URL='http://ftp.de.debian.org/debian' \
-e APTSYNC_DISTS='bullseye|main contrib|amd64' \
-v /var/www/html/debian:/data \
docker.io/ustcmirror/aptsync:latest
```
Please note the protocol of the `APTSYNC_URL`, it cannot be omitted due to the current implementation.

**Comment by RudiOnTheAir** [comment]
OK, tried it know.

I've aborted due to the permission error.. The data dir is inside the container??

`[root@debmirror aptsync]# ./aptsync.sh 
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
chown: /data/: Permission denied
deb-amd64 http://ftp.de.debian.org/debian bullseye main contrib
============ SYNC STARTED AT 2022-03-13 20:10:39 ============
*********** 8< ***********
Downloading 22 index files using 20 threads...
Begin time: Sun Mar 13 20:10:40 2022
[20]... [19]... [18]... [17]... [16]... [15]... [14]... [13]... [12]... [11]... [10]... [9]... [8]... [7]... [6]... [5]... [4]... [3]... [2]... [1]... [0]... 
End time: Sun Mar 13 20:10:43 2022

Processing translation indexes: [T]

Downloading 38 translation files using 20 threads...
Begin time: Sun Mar 13 20:10:43 2022
[20]... [19]... [18]... [17]... [16]... [15]... [14]... [13]... [12]... [11]... [10]... [9]... [8]... [7]... ^C[6]... Aborted
`

**Comment by RudiOnTheAir** [comment]
It seems, that is SE-Linux related!

I've added in the volume variable two commands found in another forum thread.

[root@debmirror ~]# cat aptsync/aptsync.sh 
docker run --rm \
    -e LOG_ROTATE_CYCLE='5' \
    -e APTSYNC_URL='http://ftp.de.debian.org/debian' \
    -e APTSYNC_DISTS='bullseye|main contrib|amd64' \
    -v /var/www/html/:/data --security-opt label=disable  \
    docker.io/ustcmirror/aptsync:latest

[https://github.com/containers/podman/issues/3683#issuecomment-517237050](url)
