### ISSUE TITLE
aptsync - Download i18n translations fails in bullseye-security

### ISSUE THREAD

**Issue by RudiOnTheAir** [ustclug/ustcmirror-images#79]
Hi

I found, that the translations in folder i18n won't download. Double slash in commandline??

The error message:
                                                                                                                                         **
Processing indexes: [Papt-mirror: can't open index security.debian.org/debian-security//dists/bullseye-security/i18n/binary-amd64/Packages in process_index at /usr/local/bin/apt-mirror line 800.
]

Maybe an idea to fix???
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=932112

My run script:

[root@debmirror aptsync]# cat debian-security.sh 
docker run --rm \
    -e LOG_ROTATE_CYCLE='5' \
    -e APTSYNC_URL='http://security.debian.org/debian-security' \
    -e APTSYNC_DISTS='bullseye-security|main contrib i18n|amd64' \
    -v /var/www/html/:/data --security-opt label=disable  \
    docker.io/ustcmirror/aptsync:latest
[root@debmirror aptsync]# 

--
Tnx in advance

**Comment by taoky** [comment]
It seems that the upstream of [apt-mirror](https://github.com/apt-mirror/apt-mirror) has stopped development, and a `sed` command can be added to https://github.com/ustclug/ustcmirror-images/blob/master/aptsync/Dockerfile to fix this bug.

BTW: It's a better idea to use rsync to sync Debian official repos instead. For Debian Security, the url is `rsync://rsync.security.debian.org/debian-security/`

**Comment by RudiOnTheAir** [comment]
> It seems that the upstream of [apt-mirror](https://github.com/apt-mirror/apt-mirror) has stopped development, and a `sed` command can be added to https://github.com/ustclug/ustcmirror-images/blob/master/aptsync/Dockerfile to fix this bug.

Why is the development stopped? Is there any alternative? I've tried debmirror, but also with problems with  debian-security.. 

> BTW: It's a better idea to use rsync to sync Debian official repos instead. For Debian Security, the url is `rsync://rsync.security.debian.org/debian-security/`

Rsync is not so easy to setup, especially if i only want to mirror only one release like bullseye amd64...

**Comment by taoky** [comment]
I have tested locally and your error message `Papt-mirror: can't open index security.debian.org/debian-security//dists/bullseye-security/i18n/binary-amd64/Packages in process_index at /usr/local/bin/apt-mirror line 800` is not relevant with [Debian bug 932112](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=932112).

The `APTSYNC_DISTS` should be `bullseye-security|main contrib|amd64` (there is no `i18n` folder in <https://security.debian.org/debian-security/dists/bullseye-security/>).

Also I'm now testing a patched version of apt-mirror and will be pushed to this repo soon.

**Comment by taoky** [comment]
@RudiOnTheAir A new version of `ustcmirror/aptsync:latest` has been pushed (<https://github.com/ustclug/ustcmirror-images/commit/a4989b30b3d19d987e992e81432ba49ffcf1ba6f>). Could you confirm that whether the i18n files can be downloaded or not (with `APTSYNC_DISTS='bullseye-security|main contrib|amd64'`)?

**Comment by RudiOnTheAir** [comment]
> I have tested locally and your error message `Papt-mirror: can't open index security.debian.org/debian-security//dists/bullseye-security/i18n/binary-amd64/Packages in process_index at /usr/local/bin/apt-mirror line 800` is not relevant with [Debian bug 932112](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=932112).
> 
> The `APTSYNC_DISTS` should be `bullseye-security|main contrib|amd64` (there is no `i18n` folder in https://security.debian.org/debian-security/dists/bullseye-security/).

Hmm, the i18n folder is inside main. And yes, i can run with no error the script, when i have removed i18n. But my debian system says, there should be such a folder.. I've putted my testmirror to the public..
-----------------
Err:7 http://home.rsdns.de:8080/debian-security bullseye-security/main Translation-en
  404  Not Found [IP: 84.134.4.79 8080]
Fetched 205 kB in 1s (325 kB/s)
Reading package lists... Done
E: Failed to fetch http://home.rsdns.de:8080/debian-security/dists/bullseye-security/main/i18n/Translation-en  404  Not Found [IP: 84.134.4.79 8080]
E: Some index files failed to download. They have been ignored, or old ones used instead.
root@pve1:~# 
----------------------

> 
> Also I'm now testing a patched version of apt-mirror and will be pushed to this repo soon.

**Comment by taoky** [comment]
Would you like to show us the contents of your `/etc/apt/sources.list`?

**Comment by RudiOnTheAir** [comment]
> Would you like to show us the contents of your `/etc/apt/sources.list`?

Sure.

deb http://home.rsdns.de:8080/debian-security/ bullseye-security main contrib

Should i put i18n to the end of the line.?? Never done that..

**Comment by taoky** [comment]
My local test shows that the `i18n/Translation-en.xz` file can be successfully downloaded. Did you pull the latest docker image (`docker pull ustcmirror/aptsync:latest`) before running again?

**Comment by RudiOnTheAir** [comment]
> My local test shows that the `i18n/Translation-en.xz` file can be successfully downloaded. Did you pull the latest docker image (`docker pull ustcmirror/aptsync:latest`) before running again?

Upps. No, i thought thats happend every time i run the script.. Btw. i'm using RockyLinux, a RHEL clone with podman.

**Comment by RudiOnTheAir** [comment]
That is it..

`root@pve1:~# apt update
Hit:1 http://home.rsdns.de:8080/debian bullseye InRelease
Hit:2 http://home.rsdns.de:8080/debian bullseye-updates InRelease
Hit:3 http://home.rsdns.de:8080/proxmox/debian/pve bullseye InRelease
Get:4 http://home.rsdns.de:8080/debian-security bullseye-security InRelease [44.1 kB]
Hit:5 http://download.proxmox.com/debian/ceph-octopus bullseye InRelease                 
Get:6 http://home.rsdns.de:8080/debian-security bullseye-security/main amd64 Packages [121 kB]
Ign:7 http://home.rsdns.de:8080/debian-security bullseye-security/main Translation-en
Get:7 http://home.rsdns.de:8080/debian-security bullseye-security/main Translation-en [77.5 kB]
Fetched 122 kB in 1s (232 kB/s)                                    
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
9 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@pve1:~# `

**Comment by RudiOnTheAir** [comment]
To understand, what do you have changed now.? I've only removed i18n after contrib. And finaly pulled your update.. ;)

**Comment by taoky** [comment]
This repo is configured with GitHub Actions, and when the master branch is pushed, it will automatically build new Docker image and push to Docker Hub.

As this issue has been resolved, I will close it :)
