### ISSUE TITLE
Git checkout image

### ISSUE THREAD

**Issue by taoky** [ustclug/ustcmirror-images#96]
我们是否需要一个专门的用于同步需要 checkout 的 git 的同步镜像？

目前 crates-io-index 是 checkout 的 git 同步，后续如果需要添加新的需要使用类似方法同步的镜像（例如 [rosdistro](https://github.com/ustclug/mirrorrequest/issues/324)），为每个镜像都写一个专门的同步容器会比较麻烦。

**Comment by knight42** [comment]
https://github.com/ustclug/ustcmirror-images/tree/master/gitsync 可以吗？

**Comment by taoky** [comment]
> https://github.com/ustclug/ustcmirror-images/tree/master/gitsync 可以吗？

是说在 gitsync 的基础上加上 checkout 的支持？

**Comment by knight42** [comment]
> 是说在 gitsync 的基础上加上 checkout 的支持？

我不太清楚具体的需求是啥样，如果不怎么需要大改 gitsync 的话可以加上试试
